### ISSUE TITLE
Unified IDE support

### ISSUE THREAD

**Issue by ChristianMurphy** [unifiedjs/ideas#1]
## Motivation

I'm working to create editor plugins for [Selective Lint](https://github.com/ChristianMurphy/selective).
https://github.com/unifiedjs/unified-engine-atom provides a good starting point for [Atom](https://atom.io).
I'd also like to create plugins for [VSCode](https://code.visualstudio.com), [WebStorm](https://www.jetbrains.com/webstorm/), [Vim](http://www.vim.org), among others.
In each of these editors I want to do basically the same thing: show inline feedback on code issues as a user types, and offer the potential to autofix where possible.

## Problem

Each editor has its own plugin API, which need to be separately developed and maintained.
In addition WebStorm and Vim run on non-javascript languages so there would need to be some extra care taken to handle binding to the JavaScript API/CLI.
All of this to communicate the *same* information, to different IDE APIs.

## Potential Solution

One promising potential solution is the [language server protocol](https://microsoft.github.io/language-server-protocol/).
Which extracts language analysis out of the editor process into a separate process, and communicates through a standard [JSON RPC](http://www.jsonrpc.org/specification) interface.
Meaning most of the processing logic lives in a shared server, and each editor implements a thin client to communicate with the server.

![](https://microsoft.github.io/language-server-protocol/img/language-server-sequence.png)
source: https://microsoft.github.io/language-server-protocol/howItWorks

At the time of writing Atom, VSCode, Sublime Text, Intellij, and Vim already have language server clients and more IDEs have support in progress.
There are also [SDK's to assist with creating a language server](https://microsoft.github.io/language-server-protocol/implementors/sdks/)

The protocol appears to support many of the features implemented by unified editor integrations already: [reporting issues inline in the IDE](https://code.visualstudio.com/docs/extensions/example-language-server#_adding-a-simple-validation) and [autofixing code](https://microsoft.github.io/language-server-protocol/specification#textDocument_formatting).

## References

* https://microsoft.github.io/language-server-protocol/
* https://langserver.org/#implementations-client
* https://github.com/Microsoft/language-server-protocol
* https://langserver.org

**Comment by ChristianMurphy** [comment]
Two examples of linters as language servers
https://github.com/shinnn/vscode-stylelint
https://github.com/Microsoft/vscode-eslint

**Comment by wooorm** [comment]
I think we need something like `unified-engine-lsp` or something to make this work, right? Are you interested in working on that?

**Comment by ChristianMurphy** [comment]
Yes and yes.
I'm wrapping up some docs updates for unified message control, then will start on vscode/language server support.

**Comment by wooorm** [comment]
@ChristianMurphy Still into this?

**Comment by ChristianMurphy** [comment]
Still into this.
Other project work is drawing my time and energy, it may be a while til I'll have time to circle back to this.

**Comment by ChristianMurphy** [comment]
I've started an initial draft at https://github.com/ChristianMurphy/unified-engine-vscode

**Comment by wooorm** [comment]
Anything I can help with?

**Comment by ChristianMurphy** [comment]
Sure,
The initial focus is getting the project to remark lint results back to the IDE.
Then generalizing to `unified-lint-rule` and `unified`.
Then adding formatting/write support.

I've been using https://github.com/shinnn/vscode-stylelint and https://github.com/shinnn/stylelint-vscode as a baseline design.

Right now the project mostly has linting and test boilerplate.
You're welcome to add functionality and features in.

**Comment by ChristianMurphy** [comment]
added in https://github.com/unifiedjs/unified-engine
